// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlmWO7cyvb5f0JhcqshK_-O7ThbxiEaIU',
    appId: '1:564112394730:web:115a20a4b274df521c0a93',
    messagingSenderId: '564112394730',
    projectId: 'chatapp-67c20',
    authDomain: 'chatapp-67c20.firebaseapp.com',
    storageBucket: 'chatapp-67c20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRKbhmO6n0kPryfaCy94uxRaf_b49dSjY',
    appId: '1:564112394730:android:85588940edb618cb1c0a93',
    messagingSenderId: '564112394730',
    projectId: 'chatapp-67c20',
    storageBucket: 'chatapp-67c20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpfzVNNq7ljgi5EbpkVtMs4lO4RxdgEd8',
    appId: '1:564112394730:ios:906eb26799cf545d1c0a93',
    messagingSenderId: '564112394730',
    projectId: 'chatapp-67c20',
    storageBucket: 'chatapp-67c20.appspot.com',
    iosBundleId: 'com.example.chapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpfzVNNq7ljgi5EbpkVtMs4lO4RxdgEd8',
    appId: '1:564112394730:ios:9be50ad2959cf2811c0a93',
    messagingSenderId: '564112394730',
    projectId: 'chatapp-67c20',
    storageBucket: 'chatapp-67c20.appspot.com',
    iosBundleId: 'com.example.chapApp.RunnerTests',
  );
}
